# Generated by Django 3.2.5 on 2021-07-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=255)),
                ('discount', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_index',
            new_name='image_url',
        ),
    ]
